# Generated by Django 4.2.3 on 2023-07-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poleron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('EG', 'EG')], max_length=2)),
                ('precio', models.CharField(max_length=20)),
                ('stock', models.IntegerField(default=1)),
                ('imagen', models.ImageField(upload_to='polerones/images')),
            ],
        ),
    ]
