# Generated by Django 4.2.3 on 2023-07-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poleron',
            options={'verbose_name': 'Polerones'},
        ),
        migrations.AlterField(
            model_name='poleron',
            name='imagen',
            field=models.ImageField(upload_to='mitienda/images'),
        ),
    ]
