# Generated by Django 4.2.3 on 2023-07-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0002_alter_poleron_options_alter_poleron_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poleron',
            name='imagen',
            field=models.ImageField(upload_to='polerones/images'),
        ),
    ]
