# Generated by Django 4.2.3 on 2023-07-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0003_alter_poleron_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('tipo_entrega', models.CharField(choices=[('Presencial', 'Presencial')], max_length=100)),
            ],
        ),
    ]
