# Generated by Django 4.2.3 on 2023-07-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0004_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('telefono', models.IntegerField(verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tipo_entrega', models.CharField(choices=[('Presencial', 'Presencial'), ('Envio', 'Envio')], max_length=100, verbose_name='Tipo de entrega')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha de solicitud')),
            ],
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.AlterField(
            model_name='poleron',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='poleron',
            name='imagen',
            field=models.ImageField(upload_to='polerones/images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='poleron',
            name='marca',
            field=models.CharField(max_length=200, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='poleron',
            name='precio',
            field=models.CharField(max_length=20, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='poleron',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='poleron',
            name='talla',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('EG', 'EG')], max_length=2, verbose_name='Tallas'),
        ),
    ]
