# Generated by Django 4.2.3 on 2023-07-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0005_interesado_delete_formulario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesado',
            name='mensaje',
            field=models.TextField(default='Sin mensaje', verbose_name='Mensaje'),
        ),
    ]
