# Generated by Django 4.2.3 on 2023-07-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0007_alter_interesado_tipo_entrega'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poleron',
        ),
    ]
