# Generated by Django 4.2.1 on 2023-08-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0010_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='titulo',
        ),
    ]
