# Generated by Django 4.0 on 2023-08-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_productos_imagen'),
        ('mitienda', '0013_presentacion_prenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion_prenda',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo.categoria'),
        ),
    ]
