# Generated by Django 4.2.3 on 2023-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poleron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('EG', 'EG')], max_length=2, verbose_name='Tallas')),
                ('precio', models.CharField(max_length=20, verbose_name='Precio')),
                ('stock', models.IntegerField(default=1, verbose_name='Stock')),
                ('imagen', models.ImageField(upload_to='polerones/images', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Polerones',
            },
        ),
    ]
