# Generated by Django 4.2.1 on 2023-07-29 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_polera_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('EG', 'EG')], max_length=2, verbose_name='Tallas')),
                ('precio', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Precio')),
                ('stock', models.IntegerField(default=1, verbose_name='Stock')),
                ('imagen', models.ImageField(upload_to='images/productos', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogo.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Chaqueta',
        ),
        migrations.DeleteModel(
            name='Polera',
        ),
        migrations.DeleteModel(
            name='Poleron',
        ),
    ]
