# Generated by Django 4.2.1 on 2023-08-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_categoria_productos_delete_chaqueta_delete_polera_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={},
        ),
    ]
