# Generated by Django 4.2.1 on 2023-08-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_rename_nombre_categoria_nombres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
