# Generated by Django 4.2.1 on 2023-08-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_remove_categoria_id_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
    ]
