# Generated by Django 4.2.4 on 2023-08-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('EG', 'EG')], max_length=2, verbose_name='Tallas')),
                ('precio', models.CharField(max_length=20, verbose_name='Precio')),
                ('stock', models.IntegerField(default=1, verbose_name='Stock')),
                ('imagen', models.ImageField(upload_to='poleras/images', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogo.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
