# Generated by Django 4.0 on 2023-08-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_alter_categoria_nombre_alter_productos_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='prendas_catalogo', verbose_name='Imagen'),
        ),
    ]
